#!/bin/sh
# -*- sh-indentation: 3 -*-
#
# genie-reweight-config a la ROOT's root-config
#

### GENIE/Reweight libraries path:
libdir=$GENIE_REWEIGHT/lib

### GENIE/Reweight src top level directory:
srcdir=$GENIE_REWEIGHT/src

### GENIE/Reweight libraries:
libs="-L$libdir -lGRwFwk -lGRwIO -lGRwClc "

### Usage
usage="\
Usage: genie-reweight-config [--libs] [--libdir] [--topsrcdir]" 

if test $# -eq 0; then
   echo "${usage}" 1>&2
   exit 1
fi

out=""

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *)    optarg= ;;
  esac

  case $1 in
    --libs)
      out="$out $libs"
      ;;
    --libdir)
      out="$out $libdir"
      ;;
    --topsrcdir)
      out="$out $srcdir"
      ;;
  esac
  shift
done

echo $out
