#!/bin/sh
# -*- sh-indentation: 3 -*-
#
# genie-reweight-config a la ROOT's root-config
#

### GENIE/Reweight libraries path:
libdir=$GENIE_REWEIGHT/lib

### perhaps "installed" and lib is not at the same level as src
if test ! -d ${libdir} ; then
  installpathline=`grep GENIE_INSTALLATION_PATH $GENIE/src/make/Make.config`
  installpathval=`echo $installpathline | cut -d= -f2`
  ### extracted string might be an env variable itself
  installpath=`eval echo $installpathval`
  if test -d ${installpath}/lib ; then
    libdir=${installpath}/lib
  fi
fi

### GENIE/Reweight src top level directory:
srcdir=$GENIE_REWEIGHT/src

### GENIE/Reweight libraries:
libs="-L$libdir -lGRwFwk -lGRwIO -lGRwClc -lGPrSp -lProfessor2"

### Usage
usage="\
Usage: genie-reweight-config [--libs] [--libdir] [--topsrcdir]" 

if test $# -eq 0; then
   echo "${usage}" 1>&2
   exit 1
fi

out=""

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *)    optarg= ;;
  esac

  case $1 in
    --libs)
      out="$out $libs"
      ;;
    --libdir)
      out="$out $libdir"
      ;;
    --topsrcdir)
      out="$out $srcdir"
      ;;
  esac
  shift
done

echo $out
